steps:
  - label: ":rust: Lint"
    commands:
      - rustup component add rustfmt
      - cargo fmt -- --check
    plugins:
      - docker#v3.3.0:
          image: 'rust:1.38-slim'

  # Build and share a debug copy of the f1-ext-install command
  - label: ":rust: :hammer: Build"
    commands:
      - rustup target add x86_64-unknown-linux-musl
      - cargo build --all --locked --target x86_64-unknown-linux-musl
    plugins:
      - docker#v3.3.0:
          image: 'rust:1.38-slim'
      - artifacts#v1.2.0:
          upload:
            - from: target/x86_64-unknown-linux-musl/debug/f1-ext-install
              to: bin/f1-ext-install
            - from: target/x86_64-unknown-linux-musl/debug/versions
              to: bin/versions

  - wait: ~

  # Run unit and doctests
  - label: ":rust: Unit tests"
    commands:
      - cargo test
    plugins:
      - docker#v3.3.0:
          image: 'rust:1.38-slim'

  # Run cheap sanity tests against selected builtin extensions
  - label: ":docker: Builtin tests"
    commands:
      - bash test/builtin.sh
    plugins:
      - artifacts#v1.2.0:
          download:
            from: bin/f1-ext-install
            to: test/f1-ext-install

  # Run sanity tests against PECL extensions
  - label: ":docker: PECL tests"
    commands:
      - bash test/pecl.sh
    plugins:
      - artifacts#v1.2.0:
          download:
            from: bin/f1-ext-install
            to: test/f1-ext-install

  - wait: ~

  # Build release image
  - label: ":docker: Build & Publish"
    branches: master
    commands:
      - bash .buildkite/build.sh
    plugins:
      - artifacts#v1.2.0:
          download: bin/versions
